### ISSUE TITLE
Consecutive executions of GetSymbols() gives inconsistent results

### ISSUE THREAD

**Issue by MikaS** [joshuaulrich/quantmod#122]
Hi,

I recently noticed that consecutive executions of `getSymbols` return inconsistent results, sometimes by omitting the last week:

``` r
> dim(getSymbols('SPY', src = "yahoo", auto.assign = F))
[1] 2441    6
> dim(getSymbols('SPY', src = "yahoo", auto.assign = F))
[1] 2435    6
> dim(getSymbols('SPY', src = "yahoo", auto.assign = F))
[1] 2435    6
> dim(getSymbols('SPY', src = "yahoo", auto.assign = F))
[1] 2441    6
> dim(getSymbols('SPY', src = "yahoo", auto.assign = F))
[1] 2435    6
> dim(getSymbols('SPY', src = "yahoo", auto.assign = F))
[1] 2441    6
> dim(getSymbols('SPY', src = "yahoo", auto.assign = F))
[1] 2435    6
```

This behavior even happens when _from_ and _to_ dates are explicitly specified.

I use Microsoft R open 64 bits on Windows 10:
R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
and the last version of quantmod: 0.4-5

Thanks,
Mikaël

**Comment by joshuaulrich** [comment]
`getSymbols.yahoo` simply returns what is provided by Yahoo Finance servers. If those servers return incorrect data, `getSymbols` will return incorrect data, and there's nothing I can do to fix it.

I just went to the [historical data page for SPY on Yahoo Finance](http://finance.yahoo.com/quote/SPY/history?p=SPY) and clicked the [Download Data](http://chart.finance.yahoo.com/table.csv?s=SPY&a=7&b=13&c=2016&d=8&e=13&f=2016&g=d&ignore=.csv) link. The CSV served to me only contained data from 2016-08-15 to 2016-09-01, even though the URL suggests the file should contain data from 2016-08-15 (because 8/13 and 8/14 were the weekend) to 2016-09-13.

The relevant portion of the URL is *&a=7&b=13&c=2016&d=8&e=13&f=2016*, where **&a** and **&d** are the months and are zero-based (i.e. January = 0).

**Comment by joshuaulrich** [comment]
Closing, since this was likely an issue with Yahoo servers and/or the user getting stale data from Yahoo's caching proxy.
