### ISSUE TITLE
getQuote rounds improperly

### ISSUE THREAD

**Issue by Masonavic** [joshuaulrich/quantmod#131]
If I use getQuote to make the following query, say to get the exchange rate between USD and Indonesian Rupiah:

`getQuote("IDRUSD=X")`

The return value is:

`                  Trade Time  Last Change % Change  Open  High   Low`
`IDRUSD=X 2016-12-16 11:00:00 1e-04      0 +0.0672% 1e-04 1e-04 1e-04`

In which the exchange rate is returned as 0.0001. The current exchange rate is 0.000075 IDR to USD. As you can see, `getQuote()` is rounding the result improperly.

**Comment by joshuaulrich** [comment]
I don't know how you determine that the current exchange rate is 0.000075 IDR to USD. `getQuote` gets its data from Yahoo Finance. And the [Yahoo Finance quote page](http://finance.yahoo.com/quote/IDRUSD=X?p=IDRUSD=X) shows 0.0001.

I'm closing this as invalid, since `getQuote` is correctly returning the data from Yahoo Finance.

**Comment by Masonavic** [comment]
Yahoo is wrong, they're rounding off:

https://www.google.com/search?q=indonesian+rupiah+to+usd
http://www.xe.com/currencyconverter/convert/?From=IDR&To=USD
https://www.bloomberg.com/quote/USDIDR:CUR

Is there any way to use a separate data source than yahoo?

**Comment by joshuaulrich** [comment]
No other data sources are currently implemented.
