### ISSUE TITLE
quantmod `getSymbols.yahoo` uses incorrect date (month number) and creating invalid URL

### ISSUE THREAD

**Issue by patamat1** [joshuaulrich/quantmod#132]
I am trying to download data of the symbol MACQ by applying the following code: 
getSymbols.yahoo("MACQ",.GlobalEnv,from="2010-02-02",to="2016-12-28")

However, I am getting error warning:

Error in download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  : 
cannot open URL 'http://ichart.finance.yahoo.com/table.csv?s=MACQ&a=1&b=02&c=2010&d=11&e=28&f=2016&g=d&q=q&y=0&z=MACQ&x=.csv'
In addition: Warning message:
In download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  :
cannot open URL 'http://ichart.finance.yahoo.com/table.csv?s=MACQ&a=1&b=02&c=2010&d=11&e=28&f=2016&g=d&q=q&y=0&z=MACQ&x=.csv': HTTP status was '404 Not Found'

From the message above you can see, that the following url is being used: 'http://ichart.finance.yahoo.com/table.csv?s=MACQ&a=1&b=02&c=2010&d=11&e=28&f=2016&g=d&q=q&y=0&z=MACQ&x=.csv'

If you copy/paste this url into web browser you will really encounter Yahoo! 404 Not Found Problem.

However if you look carefully at the URL, you will notice, that it is using incorrect date reference in the url and thus creating invalid url link. The first "mistake" is that the starting date (i.e. the month) is written in the url as 1&b, but it should have been written as 02&b and also the the end month 11&e should have been 12&e.

So the link: http://ichart.finance.yahoo.com/table.csv?s=MACQ&a=1&b=02&c=2010&d=11&e=28&f=2016&g=d&q=q&y=0&z=MACQ&x=.csv

should have looked like this: http://ichart.finance.yahoo.com/table.csv?s=MACQ&a=02&b=02&c=2010&d=12&e=28&f=2016&g=d&q=q&y=0&z=MACQ&x=.csv

Why is incorrect date used and how to prevent it? This happened to me only when using "MACQ" symbol.

Also posted this on stackoverflow and was recommended to report issue here.
http://stackoverflow.com/questions/41510802/quantmod-getsymbols-yahoo-uses-incorrect-date-month-number-and-creating-inva?noredirect=1#comment70227741_41510802

**Comment by joshuaulrich** [comment]
> If you copy/paste this url into web browser you will really encounter Yahoo! 404 Not Found problem.

Correct.

> However if you look carefully at the URL, you will notice, that it is using incorrect date reference in the url and thus creating invalid url link. The first "mistake" is that the starting date (i.e. the month) is written in the url as 1&b, but it should have been written as 02&b and also the the end month 11&e should have been 12&e.

You are incorrect. The months *should* zero-based, not one-based as you suggest.

> Why is incorrect date used and how to prevent it? This happened to me only when using "MACQ" symbol.

Again, the dates are not incorrect. I don't know why this only happens using `"MACQ"`, you would have to ask someone at Yahoo Finance.  It probably has something to do with the very short amount of history available for this security.  The oldest observation on the [historical data page for MACQ](http://finance.yahoo.com/quote/MACQ/history?p=MACQ) is 2016-12-23.  If you download all the data for `"MACQ"`, you only get 2017-01-03 through 2017-01-05.

```r
> getSymbols("MACQ")
[1] "MACQ"
> MACQ
           MACQ.Open MACQ.High MACQ.Low MACQ.Close MACQ.Volume MACQ.Adjusted
2017-01-03     10.04     10.04    10.04      10.04        2800         10.04
2017-01-04     10.04     10.04    10.04      10.04         700         10.04
2017-01-05     10.04     10.04    10.04      10.04           0         10.04
```

I'm closing this as invalid, because there's nothing `quantmod::getSymbols` can do to correct for the Yahoo Finance server denying a valid query.

Also note that you should not call `getSymbols.yahoo` directly (as it says in `?getSymbols.yahoo`).

**Comment by patamat1** [comment]
Thank you for the reply.
