### ISSUE TITLE
R getsymbols

### ISSUE THREAD

**Issue by sunzhouziguang** [joshuaulrich/quantmod#185]
getSymbols("APPL",scr="yahoo",from="2013-10-01",to="2013-10-23")
Warning: APPL download failed; trying again.
Error: APPL download failed after two attempts. Error message:
HTTP error 404.

Why can't this function be used? how to resolve this problem? thank you very much

**Comment by selgamal** [comment]
@sunzhouziguang  Try "AAPL", ticker symbol "APPL" doesn't exist

**Comment by sunzhouziguang** [comment]
> getSymbols("0001979.ss",src='yahoo',from="2013-08-20",to="2016-09-02")
Warning: 0001979.ss download failed; trying again.
Error: 0001979.ss download failed after two attempts. Error message:
HTTP error 404.
> I can't get Chinese stock data now, from YAHOO Finance.My teacher said, YAHOO finance changed the link, need to download the new QUANTMOD, what should I do?

**Comment by joshuaulrich** [comment]
@sunzhouziguang Have you installed the latest quantmod from CRAN?  I don't know because you didn't provide the output from `sessionInfo()` like the issue template asked you to.

The issue with `"0001979.ss"` is the same as with `"APPL"`, it is not a valid ticker symbol.  The first obvious problem is that you've provided 7 digits, when Chinese stocks are specified by only 6 digits.

The other problem is that `"001979"` is traded on the Shenzhen exchange (suffix SZ), not Shanghai (suffix SS).  So the symbol should be `"001979.SZ"`.

As the [contributing guide](
https://github.com/joshuaulrich/quantmod/blob/master/CONTRIBUTING.md) asks, "Please do not open an issue to ask a question about how to use the package. Instead, ask your question on [Stack Overflow](http://stackoverflow.com/questions/tagged/r) or the [R-SIG-Finance](https://stat.ethz.ch/mailman/listinfo/r-sig-finance) mailing list (you must subscribe to post)."
