### ISSUE TITLE
Google as data source

### ISSUE THREAD

**Issue by helgasoft** [joshuaulrich/quantmod#188]
Recent problems with Yahoo stock data (https://github.com/joshuaulrich/quantmod/issues/174) have generated interest in alternative data sources. One available in quantmod is Google thru *getSymbols(x, ..., src='google')*.  
There is an problem however, related to Google's interpretation of ticker symbols. Here is an example:
```r
getSymbols('WEX', from='2017-08-28', to=Sys.Date(), env=parent.frame(), src='google') 	# not found
getSymbols('NYSE:WEX', from='2017-08-28', to=Sys.Date(), env=parent.frame(), src='google') # all's cool
```
In order to get valid OHLC data, one must **prefix all symbols with their exchange codes**.
getSymbols uses http://finance.google.com/finance/historical?q=SYMBOL to get the data (why not https: ?).
Here are more examples:
* a1. https://finance.google.com/finance/historical?q=VLU		missing
* a2. https://finance.google.com/finance/historical?q=NYSEARCA:VLU	SPDR Series Trust
* b1. https://finance.google.com/finance/historical?q=XE		Xemplar Energy Corp(CVE:XE.H)
* b2. https://finance.google.com/finance/historical?q=BATS:XE	Elkhorn S&P Energy Portfolio(BATS:XE)
* c1. https://finance.google.com/finance/historical?q=ABE		Abertis Infraestructuras S.A.(BME:ABE)
* c2. https://finance.google.com/finance/historical?q=NYSEMKT:ABE	Aberdeen Emrg (NYSEMKT:ABE)

Cases **b1** and **c1** show that one may get data for a **completely different** company if the exchange prefix is **not** used.

Some help on solving the problem by finding Google exchange prefix for all US symbols:
http://ftp.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt  will list all symbols with prefix 'NASDAQ'.
http://ftp.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt will have the following:

Code | Google Prefix | Google Example
--- | --- | ---
P | NYSEARCA | SPDR S&P Pharmaceuticals (NYSEARCA:XPH)
N | NYSE | Visteon Corp(NYSE:VC)
A | NYSEMKT | eMagin Corporation(NYSEMKT:ESP)
Z | BATS | Alpha Architect Value Momentum Trend ETF(BATS:VMOT)

Of course there is nothing wrong with quantmod. I'm just sharing an usage issue with Google data source.

**Comment by joshuaulrich** [comment]
Thanks a lot for the report and detailed information!  Do I understand correctly that you're suggestion is to use the nasdaqtrader.com files to create a lookup table for symbol -> exchange?  Or did I misunderstand?

Also seems like it would be a good idea to throw a `warning()` if the user did not specify an exchange, since the symbol may be ambiguous.

Regarding why `getSymbols.google()` uses "http" instead of "https": simple, Google hasn't killed the "http" URL. ;-)  Switching to "https" is a good idea, and I'll make sure that happens.

**Comment by helgasoft** [comment]
I found the nasdaqtrader.com links in quantmod's code. It wasn't a suggestion, but since the data is already read, why not, an exchange lookup table would be a good addition to quantmod.

**Comment by ethanbsmith** [comment]
As of about 10 years ago ( i cannot remeber the date), the US exchanges implemented a policy of cross exchange symbol uniqueness. i.e. you can no longer have the same symbol on more than 1 US exchange. So, the above issue will only affect you when hitting symbols that are valid on international exchanges. The nasdaq files only cover US based listings, but this can still theoretically help a bit. I have found the most useful nasdaq file to be ftp://ftp.nasdaqtrader.com/symboldirectory/nasdaqtraded.txt, since this covers most major US exchanges in a single file. It does not include OTC listings, but neither do the other files. besides, getting an exhaustive list of all forms OTC securities without paying is non-trivial

google also creates and uses some dummy exchange codes that will not be found in the nasdaq file . Examples include : INDEXxxxx (INDEXCBOE, INDEXDJX, INDEXSP...) , MUTF, CURRENCY
https://finance.google.com/finance?q=INDEXCBOE%3AVIX
https://finance.google.com/finance?q=INDEXDJX%3A.DJI
https://finance.google.com/finance?q=MUTF%3AFLPSX
https://finance.google.com/finance?q=INDEXSP%3A.INX

Also note that the nasdaq files use their own symbology rules. class shares eg: BRK.A, BRK.B work fine with google, but you still probably need to test edge cases around warrants, preferreds, rights offerings, etc. eg: ABR$A vs ABR-A on google

For what its worth, most countries have adopted similar uniqueness rules within each country. So I'm not sure why google implemented their API the way they did. they could have just used a country prefix instead of an exchange

given all this, an easy (though not fast) solution would that when you encounter a failure on the raw symbol, try again with each google US exchange prefix (including the dummy index exchange and such) in order.

A bit of a rant, but I hope some of this at least is useful

**Comment by helgasoft** [comment]
Useful indeed.  The [file](ftp://ftp.nasdaqtrader.com/symboldirectory/nasdaqtraded.txt) contains 8464 symbols in 6 exchanges, which I found to be the following:

abbreviation | records | prefix example | exchange name
--- | --- | --- | ---
 A | 356 | NYSEMKT:ABE | NYSEMKT (AMEX)
 N | 3138 | NYSE:AAP | NYSE
 P | 1462 | NYSEARCA:XPH | NYSEARCA
 Q | 3267 | NASDAQ:AAME | NASDAQ: Global Select(large cap) + Global Market(mid cap)
 V | 3 | - | IEX (test only)
 Z | 237 | BATS:ARCM | BATS

Prefixes are needed.  Just try the first [ABE](https://finance.google.com/finance/historical?q=ABE) or last [ARCM](https://finance.google.com/finance/historical?q=ARCM) without the prefix, and see how Google picks up a different foreign exchange symbol.
Now that Yahoo seems to be closing their financial API [data sources](http://download.finance.yahoo.com/d/quotes.csv?s=IBM&f=d1t1nohgl1v), maybe it's time for this to be included in quantmod.
