### ISSUE TITLE
Google Finance no longer providing data

### ISSUE THREAD

**Issue by lerenardmewa** [joshuaulrich/quantmod#221]
getFinancials no longer retrieves financial data from Google Finance:

> getFinancials("AAPL")
Error in download.file(paste(google.fin, Symbol, sep = ""), quiet = TRUE,  : 
  cannot open URL 'http://finance.google.com/finance?fstype=ii&q=AAPL'
In addition: Warning message:
In download.file(paste(google.fin, Symbol, sep = ""), quiet = TRUE,  :
  cannot open URL 'http://finance.google.com/finance?fstype=ii&q=AAPL': HTTP status was '404 Not Found'

Moreover, seems like Google is no longer providing this info.

**Comment by mtbakerguy** [comment]
Trying it on OSX, you get the following:

> getFinancials('AAPL',auto.assign=FALSE)
Error in thead[x]:thead[x + 1] : NA/NaN argument
> 

Looking at the (still HTTP; yay!) packet trace: it looks like there's a redirect.

**Comment by msmith01** [comment]
I get the same error

`Error in thead[x]:thead[x + 1] : NA/NaN argument`

Also using; `quantmod::getFin("COP")`

Error:

```
Error in get(Info[i, 1], envir = env) : 
  lazy-load database 'C:/Users/USER/Documents/R/win-library/3.4/quantmod/R/quantmod.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
```

I have deleted, reinstalled in many different ways and still the same problem.

**Comment by Solernova** [comment]
It seems as though Google is selectively blocking the getSymbols query and it is affecting the rest of the code base. 
<img width="1157" alt="screen shot 2018-03-21 at 2 07 00 pm" src="https://user-images.githubusercontent.com/18154201/37728732-6e33f2c0-2d11-11e8-8bfa-52b1545365a5.png">

**Comment by msmith01** [comment]
Has Google completely removed financial accounts from their service altogether?

https://www.google.com/search?q=NASDAQ:AAPL&tbm=fin#scso=uid_m7i2WrSfDML1Uv7jtNAK_5:0

Reveals no annual accounts for AAPL... Is it possible to change the default source from finance.google to finance.yahoo?

**Comment by joshuaulrich** [comment]
Thanks for the report.  The original comment only mentioned `getFinancials()`, but `getSymbols.google()` is also no longer working.  It appears Google has simply stopped providing historical prices, and the financials provided on their website are very limited.  That suggests to me that functions that request data from Google should either be marked as defunct, and/or use another source.

@msmith01: I cannot change the default source from Google to Yahoo because there is no implementation that uses Yahoo as a source.  I'm not inclined to work on scraping/parsing the financial data from Yahoo, so someone else would need to do it.

**Comment by joshuaulrich** [comment]
Does anyone have thoughts/opinions whether `getSymbols.google()` should use `.Deprecated()` or `.Defunct()` versus passing the call to `getSymbols.yahoo()`?

**Comment by ethanbsmith** [comment]
since google does not follow the same rules as yahoo on splits nor does it use the same extended symbology as yahoo, pointing .google calls to .yahoo is setting people up for subtle errors. I would just warn that the functionality is not supported and people should port to .yahoo calls. just my $.02

**Comment by msmith01** [comment]
@joshuaulrich and to others who want to download fundamental data. There was an interesting post over at Stackexchange, somebody wrote a script to collect financial data from yahoo. Heres the[ post](https://stackoverflow.com/questions/49452906/getfinancials-quantmod-and-tq-get-tidy-quant-not-working). Alternatively running the following takes some financial information from ADVFN website (but not great).

`con = gzcon(url('http://www.systematicportfolio.com/sit.gz', 'rb'))
source(con)
close(con)
GOOG <- fund.data("GOOG")`
