### ISSUE TITLE
Missing Last Trading Session's Data

### ISSUE THREAD

**Issue by ivanoliveri** [joshuaulrich/quantmod#237]
### Description

Today is 2018-05-21, around 11pm in Argentina. Here the stock market closes at 5pm. I tried to pull the data using quantmod but the latest date available is 2018-05-18. However, the data is avalialbe for 2018-05-21 on Yahoo Finance's page.

### Expected behavior

Get the data until the latest date available on Yahoo Finance.

### Minimal, reproducible example

```r
library(quantmod)

library(dplyr)

pamp.out <- getSymbols(Symbols = c("PAMP.BA"),
                       src="yahoo", 
                       auto.assign = F)

df.pampa <- pamp.out %>%
            as.data.frame(.) %>%
            mutate(date = row.names(.) %>% as.Date())

print(paste0("Max Data Available: ",
             df.pampa %>% pull(date) %>% max(),
             "; Today is: ",
             Sys.Date()))
```

### Session Info

```r
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=C                             

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] quantmod_0.4-13.1   BatchGetSymbols_2.1 TTR_0.23-3          xts_0.10-2          zoo_1.8-0           bindrcpp_0.2       
 [7] rvest_0.3.2         xml2_1.1.1          ggthemes_3.5.0      ggplot2_2.2.1       stringr_1.2.0       RcppRoll_0.2.2     
[13] tidyr_0.7.1         dplyr_0.7.3         lubridate_1.6.0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     git2r_0.18.0     compiler_3.4.0   plyr_1.8.4       bindr_0.1        tools_3.4.0      digest_0.6.12   
 [8] memoise_1.1.0    tibble_1.3.3     gtable_0.2.0     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.2      curl_3.2        
[15] knitr_1.15.1     withr_1.0.2      httr_1.3.1       devtools_1.13.5  grid_3.4.0       glue_1.1.1       R6_2.2.2        
[22] purrr_0.2.2      magrittr_1.5     scales_0.5.0     assertthat_0.2.0 colorspace_1.3-2 stringi_1.1.5    lazyeval_0.2.0  
[29] munsell_0.4.3   
```

**Comment by joshuaulrich** [comment]
`getSymbols.yahoo()` imports whatever data is returned by the Yahoo Finance servers.  It cannot affect when the current day's data are made available on the remote server, so there is nothing I can do to change this behavior.

In the future, please make reproducible examples *minimal*. Using `dplyr` requires I install more than a dozen packages, and is not necessary to reproduce the behavior.

**Comment by rexmacey** [comment]
While I think I understand why the code can't be "fixed", I beg the community to warn users of this behavior in their documentation.  I think most users would expect the code below to return prices for 2018-11-30, but it only returns data through 2018-11-29.  

`from <- as.Date("2018-06-30")
to <- as.Date("2018-11-30")
qm <- getSymbols("SPY", from = from, to=to)
`

**Comment by braverock** [comment]
@rexmacey quantmod doesn't control yahoo.

What warning would you anticipate?  If you had used '2018-12-01' as the to date? would you expect a warning that Saturday isn't a market day for 'SPY'?  How would quantmod know that?

Maintaining instrument metadata is an extremely complex task (so much so that we created a separate package for it).

most getSymbols methods for quantmod simply go to the data source, parse the returned data, and do their best to make it meaningful.  Yahoo is a poor and getting worse data source.  Perhaps you should consider using a more reliable and commercial source?

**Comment by rexmacey** [comment]
That was a fast response.  Please know that I am grateful for the work you do.  

 

Here’s what I would expect as a warning and perhaps I should have been explicit that I would suggest a warning in the documentation rather than a warning to be generated by the function.  In the documentation (help) for getSymbols.yahoo and perhaps for getSymbols, the Details section might include wording to the effect that 

When the ‘to’ parameter is specified, the data may not include data through the ‘to’ date even if prices are available for the that date.

 

Specifically I might consider rewording the getSymbols.yahoo documentation for the ‘to’ argument which currently reads: “Retrieve data through this date (Sys.Date())”.  It seems to me that is misleading as it seems to “Retrieve data up to this date” or “Retrieve data up to but not including this date”.  

 

I would further suggest that vignettes with the getSymbol function illustrate the behavior by showing the results of a tail function.

 

If I had used 2018-01-01, I would not have expected a result for that date.  

 

Whatever you decide, I appreciate your attention to this matter.

**Comment by ethanbsmith** [comment]
maybe the following text should be added to the getSymbols.yahoo docs under the Waning section:

In addition, the Yahoo Finance API is know to sometimes return data that are inconsistent with the data displayed on the Yahoo Finance web pages. This includes both missing data as well as different values. Caveat Emptor!
