### ISSUE TITLE
getsymbols.Yahoo retriving wrong value for CUP/USD=x currency symbol

### ISSUE THREAD

**Issue by sureshvigneshbe** [joshuaulrich/quantmod#277]
CUP/USD  currency  Conversion rate  is  0.0377358491. However getsymbols.Yahoo retriving wrong value  as  1.027855  and it continues for every day. 

Please help whether it can be fixed. Also Kindly share the list of currency symbols supported by getsymbols.Yahoo.

Quantmod package used. 

R version:                     
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer

**Comment by sureshvigneshbe** [comment]
Kindly share the list of currency symbols supported by getsymbols.Yahoo.

**Comment by joshuaulrich** [comment]
Hi @sureshvigneshbe.  I don't have a list of currency symbols that Yahoo Finance supports.  You could try to search their website.  I also can't do anything in quantmod to fix when a data provider returns incorrect data.  You could try using a different data provider, like Oanda or Tiingo.  You could also try FRED or Quandl (using their package).

I'm going to close this because there's nothing I can do in quantmod to fix it, but please feel free to continue to ask follow-up questions.  I'll do what I can to help.
