### ISSUE TITLE
Bug in getDividends

### ISSUE THREAD

**Issue by Dro1000** [joshuaulrich/quantmod#290]
### Description

Hi! 
It seems that getDividends adjusted dividends for splits twice.
### Expected behavior

For example, function quantmod::getDividends("AAPL") return xts object, where on 2014-05-08 its value is 0.067142 = 3.29 / 49, but valid value must be 0.47 = 3.29 / 7. I think,  the function adjusts already adjusted data.

**Comment by helgasoft** [comment]
The _split.adjust_ parameter is TRUE by default. I do not know weather this is correct or not. But by setting it to FALSE, you get the value you want:
```
quantmod::getDividends("AAPL", split.adjust=FALSE)['2014-05-08'] 
```

**Comment by joshuaulrich** [comment]
I think `getDividends()` is correct here, because it adjusts for splits by default.

According to [AAPL's website](https://investor.apple.com/dividend-history/default.aspx), there was a 7-for-1 stock split on 2014-06-09 and a $0.47 dividend on 2014-08-14.  `getDividends()` returns the split-adjusted dividends by default, so $0.067142 = 0.47/7.

There are [unit tests](https://github.com/joshuaulrich/quantmod/blob/afb79aaea3f10c7367f9feeead6b14503e703b0f/tests/test_getDividends.R#L7) that should fail if Yahoo changes how they return data.

**Comment by helgasoft** [comment]
The table below shows a comparison between [Apple data](https://investor.apple.com/dividend-history/default.aspx) and Yahoo data thru _quantmod::getDividends("AAPL", split.adjust=**FALSE**)_.

date | apple | yahoo | calc yahoo
--- | --- | --- | ----
1995-xx-xx | .12 | 0.00429 | .12/2/2/7
2000-06-21 | 2-for-1 | _ | _
2005-02-28 | 2-for-1 | _ | _
2012-08-09 | 2.65 | 0.37857 | 2.65/7
2014-05-08 | 3.29 | 0.47000 | 3.29/7
2014-06-08 | 7-for-1 | _ | _
2014-08-07 | 0.47 | 0.47 | since then apple=yahoo

After a split, prior data gets adjusted. Looks like Yahoo **AAPL dividends are coming already adjusted**. And, as @Dro1000 pointed out, _quantmod::getDividends_ is indeed adjusting them twice.
However, after checking the unit tests for CF and a couple more big companies like IBM,NKE,V with recent splits, it seems that _quantmod::getDividends_ is working correctly.
Which brings the conclusion that the bug is in Yahoo data for AAPL (and maybe others...)
