### ISSUE TITLE
getOptionChain: object 'bid' not found

### ISSUE THREAD

**Issue by mathieu-lemire** [joshuaulrich/quantmod#338]

**Comment by joshuaulrich** [comment]
I assume you deleted your comment because it had already been fixed. I restored it so it wouldn't confuse me or others in the future. Don't worry if you accidentally report something that's been fixed. It happens.

I ask people to make sure to use the most recent development version so they don't spend time hunting down bugs that have been fixed; out of respect for your time. :wink: 

Duplicate of #300.
