### ISSUE TITLE
getOptionChain function is returning NA on bid ask for ETF's

### ISSUE THREAD

**Issue by imangini** [joshuaulrich/quantmod#365]
### Description

Whenever I run getOptionChain(...) on a vector of assets. I'm only getting the data for stocks, but for ETF's like SPY and QQQ, the bid ask prices for the options is NA.

### Expected behavior
![Screenshot 2022-11-17 at 15 36 31](https://user-images.githubusercontent.com/117315454/202530085-140406ba-9524-4bee-b436-e95b74000791.png)

As you can see here with AAL ticker, we have all bid and ask prices.

### Erroneous Behavior

![Screenshot 2022-11-17 at 15 37 49](https://user-images.githubusercontent.com/117315454/202530306-252dcad6-e12c-4bf3-80a4-b74356d7de9e.png)

And here is the output for SPY. Note that there are option for 2022-11-17, so it's not a problem that the option's expiry does not exist. See the image below for the market data for SPY for the mentioned date.

![Screenshot 2022-11-17 at 15 28 16](https://user-images.githubusercontent.com/117315454/202530547-90c5b588-496f-4a1d-93f4-85891021373c.png)

### Minimal, reproducible example

```r
asset_options <- getOptionChain(c("AAL", "SPY"))
```

### Session Info

![Screenshot 2022-11-17 at 15 34 09](https://user-images.githubusercontent.com/117315454/202529688-116289ed-0326-4757-82bd-f51500ee9fc2.png)

**Comment by joshuaulrich** [comment]
Yahoo doesn't show bid/ask prices for them on its website either. So I'm closing this because I don't think there's anything I can do. I'm happy to continue discussing it though.

Regardless, these expire today. I wouldn't trust their prices enough to use them. I'm not familiar with options on ETFs, but it's possible their last trading day and settlement procedures are different than stocks.


![image](https://user-images.githubusercontent.com/1023193/202546300-b6a9741f-d3e3-4d27-a40d-e563f103b77b.png)
