### ISSUE TITLE
Oil prices

### ISSUE THREAD

**Issue by 097115** [joshuaulrich/quantmod#54]
Is there any way to get historical oil (WTI, Brent) prices with `quantmod`? Any hint, may be? (yes, I know that futures are traded in contracts by months...)

**Comment by braverock** [comment]
On 05/28/2015 10:46 PM, 097115 wrote:
> Is there any way to get historical oil (WTI, Brent) prices with
> |quantmod|? Any hint, may be? (yes, I know that futures are traded in
> contracts by months...)

No, but quandl has some futures data, and is easy to use from R.

**Comment by 097115** [comment]
Thanks, Brian. Yeah, I know about Quandl, use it quite a lot. Just wanted to simplify my routine a bit, to get everything I need from one provider...

**Comment by rsvp** [comment]
See fecon235, for example, https://github.com/rsvp/fecon235/blob/master/nb/fred-oil-brent-wti.ipynb which uses cash prices to model the Brent-WTI spread -- but futures is accessible too, for example, by merely: get('f4wti16m').

**Comment by joshuaulrich** [comment]
@rsvp I spent a few minutes looking at that IPython notebook, and I don't understand why you mentioned it. Plus, you say that "futures is accessible too, for example, by merely: get('f4wti16m')." But I don't see any reference to `get('f4wti16m')` in the IPython notebook, and there is no "f4wti16m" on FRED.

**Comment by rsvp** [comment]
@joshuaulrich The futures prices were not used in that particular notebook because rollovers would somewhat distort the long-term spread picture. Journalists frequently get freaked out when they do not understand why jumps occur around rollover dates. 

Retrieving futures prices actually does not rely on FRED, but rather Quandl in the background. And that access code is for our convenience (you could also enter the actual Quandl code in all caps). So as a straight example:

`
from fecon235 import fecon235 as fe
wti = fe.get('f4wti16m')
#  wti is thus a pandas dataframe for West Texas Intermediate, June 2016 futures.
`

... two lines of code, easy to see how that could be incorporated within a Jupyter notebook.

The "get" function can also retrieve other financial time-series, e.g. get('s4oil') retrieves the ETF iPath S&P GSCI Crude Oil Total Return. It's fully documented at  https://github.com/rsvp/fecon235

**Comment by joshuaulrich** [comment]
@rsvp Then I'm afraid I don't understand what your comment adds to the discussion. The initial reply to the question said that the data could be retrieved via Quandl. And there's a Quandl R package, so I'm really confused why you're mentioning Python.

**Comment by rsvp** [comment]
@joshuaulrich The straight answer to the original question is that quantmod is incapable of handling futures data. That settled, what's the alternative? Certainly the Quandl R package, but it is not as straightforward as two lines of fecon235 code, which granted. is in Python.

Two different languages should not present an artificial barrier to a simple alternative. Two useful examples: a shell script could easily integrate results, a Jupyter notebook running a R kernel could easily run "%%python" code in one of its cells.

Sometimes a (hopefully) helpful discussion goes beyond the strict bounds of an explicit question. After all, the bigger implicit goal is just to get the data analysis DONE fast. Is that understandable?

**Comment by joshuaulrich** [comment]
@rsvp It seems very odd to say that `wti <- Quandl::Quandl("ICE/TM2016")` is "not as straightforward as two lines of fecon235 code". And using a different language does present a real (not artificial) barrier, to a person who says that they "want to simplify their routine". 

I understand fecon235 is your project, and you wish to promote it. But I respectfully ask that you do not do it on my issue trackers. These trackers are for issues related to the code contained in their respective repositories. I do not want content pushed at me that is not relevant to my projects. I simply do not have time for that.
