### ISSUE TITLE
Unnecessary warning message?

### ISSUE THREAD

**Issue by kendonB** [joshuaulrich/quantmod#68]
# quantmod_0.4-4
    getSymbols('F')  
    [1] "F"
    Warning message:
      In download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  :
                               downloaded length 116669 != reported length 200

I'm on R 3.2.1 and Windows 8.1.

**Comment by joshuaulrich** [comment]
We can't control that. We call `download.file` with `quiet = TRUE`, but it sill prints those warnings because the HTTP response length is 200, but the CSV length is not.

You're also using an old version of quantmod. Please only report issues on the latest development version (or, at the very least, the latest version on CRAN).
