### ISSUE TITLE
getSymbols.yahoo broken

### ISSUE THREAD

**Issue by SamoPP** [joshuaulrich/quantmod#70]
It looks like yahoo changed (again) the url for historical data. Instead of ichart they use real-chart now: http://real-chart.finance.yahoo.com/table.csv?s=SPY&d=10&e=18&f=2015&g=d&a=0&b=29&c=1993&ignore=.csv

**Comment by joshuaulrich** [comment]
Thanks for the report. The current code still works for me, but that may be because my request is going to a server that still supports the current URL.

Can you please provide the evidence that made you suspect that `getSymbols.yahoo` is broken due to a URL change? And did you test any of the other functions that pull data from Yahoo Finance (i.e. `getDividends`, `getSplits`, `getQuote`, `getOptionChain`, `getSymbols.yahooj`)?

**Comment by SamoPP** [comment]
Joshua, it looks like it might have been location specific. I mean, it works now, when I am back home. When I reported the error I was in Warsaw, Poland and it did not work. So consider this closed. Thanks.
