### ISSUE TITLE
What is the difference between the 3 Delt functions?

### ISSUE THREAD

**Issue by john-a-m** [joshuaulrich/quantmod#82]
It looks like there are three Delt functions at the end of https://github.com/joshuaulrich/quantmod/blob/master/R/OHLC.transformations.R ... each one is slightly different and there is a lot of code duplication. I'm new to R so this might be how things are supposed to be done, I don't know. Edit: I don't know how to add a help wanted tag, but that's what I'm asking for.

**Comment by joshuaulrich** [comment]
I'm closing this because it's not reporting an issue or feature request.  This issue tracker is not the place to ask for help or discuss general R programming advice.  If you want to discuss further, you can email me privately.

To briefly address your question: only `Delt` is exported, so the other 2 aren't exposed to users.  A quick `grep` of the code indicates `.Delt` is never used anywhere, so it's likely a historical artifact.  And `Delt_` is only used in `periodReturn`. And code duplication is generally a bad practice because it makes debugging and maintenance more difficult.

Regarding your edit: you can't add labels. Labels are so contributors can organize issues.
