### ISSUE TITLE
Guidance on aggregating daily technical indicators to monthly indicators

### ISSUE THREAD

**Issue by debsush** [joshuaulrich/quantmod#91]
Hi,

This is again not an issue but a query seeking your guidance.  I tried the query over Cross-Validated but it yielded no response.  I had a basic question on technical indicators.

Suppose I have daily (PDaily) and monthly price (PMonthly) data. When I calculate daily AroonUp/Down, I can use

    aroonTAdaily<-aroon(HL=fPDaily[,c("High","Low")],n=20)

Now when I change the chart period to monthly which of the following 2 approaches should I take: 

**Approach 1:** Aggregate the aroonTAdaily

    aroonTAMonthly <- to.monthly(aroonTAdaily, drop.time=TRUE,OHLC=FALSE)

**Approach 2:** Use the monthly price data directly

    aroonTAMonthly <-aroon(HL=fPMonthly[,c("High","Low")],n=20)

Please guide me on the correct approach.

**Comment by joshuaulrich** [comment]
This isn't the right forum for seeking guidance about how to do particular analysis. I suggest you send an email to [R-SIG-Finance](https://stat.ethz.ch/mailman/listinfo/r-sig-finance) (you need to subscribe to post).

The correct approach would depend on what you plan to do with the result, which isn't clear from your question. Your question on Cross Validated was closed because it was unclear.  I suggest you take that feedback and try to make your question clearer before posting elsewhere.

**Comment by debsush** [comment]
Thank you.  I will take your approach and take help from R-SIG-Finance
